name: refilc_mobile_ui
publish_to: "none"

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # reFilc Main
  refilc:
    path: ../refilc/
  # e-KRETA API (kreten) client
  refilc_kreta_api:
    path: ../refilc_kreta_api/
  # reFilc Plus
  refilc_plus:
    path: ../refilc_plus/

  flutter_feather_icons: ^2.0.0+1
  provider: ^6.1.2
  fl_chart: ^0.68.0
  url_launcher: ^6.3.1
  flutter_material_color_picker: ^1.2.0
  photo_view: ^0.15.0
  flutter_linkify: ^6.0.0
  flutter_custom_tabs: ^2.1.0
  flutter_markdown: ^0.7.6+2
  animations: ^2.0.11
  animated_list_plus: ^0.5.2
  confetti: ^0.8.0
  # live_activities: ^1.9.1+1
  animated_flip_counter: ^0.3.4
  lottie: ^3.3.1
  rive: ^0.12.4
  animated_background: ^2.0.0
  home_widget: ^0.7.0+1
  dropdown_button2: ^2.3.9
  flutter_svg: ^2.0.17
  background_fetch: ^1.3.7
  wtf_sliding_sheet: ^1.1.3
  package_info_plus: ^8.2.1
  dotted_border: ^2.1.0
  screenshot: ^3.0.0
  image_gallery_saver_plus: ^3.0.5
  rounded_expansion_tile: ^0.0.13
  flutter_expandable_fab: ^2.3.0
  intl: ^0.19.0
  i18n_extension: ^12.0.1
  auto_size_text: ^3.0.0
  connectivity_plus: ^6.1.3
  collection: ^1.19.0
  share_plus: ^10.1.4
  image_picker: ^1.1.2
  path_provider: ^2.1.5
  image_crop_plus: ^1.0.0
  uuid: ^4.5.1
  maps_launcher: ^3.0.0+1
  google_fonts: ^6.2.1
  custom_sliding_segmented_control: ^1.8.5
  get_it: ^7.7.0
  xml: ^6.5.0
  markdown: ^7.3.0
  carousel_slider: ^5.0.0
  flutter_portal: ^1.1.4
  webview_flutter: ^4.10.0
  file_picker: ^8.3.7
  shake_flutter: ^17.1.0
  qr_code_scanner_plus: ^2.0.10+1
  wakelock_plus: ^1.2.10
  
dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
